import type { Metadata } from "next";
import { Geist, Geist_Mono,Volkhov } from "next/font/google";
import "./globals.css";
import "@/styles/globals.scss"


const volkhov = Volkhov({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable:'--font-volkhov',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${volkhov.variable}`}>
        {children}
      </body>
    </html>
  );
}
