import type { Metadata } from "next";
import { Volkhov } from "next/font/google";
import "./globals.css";
import "@/styles/globals.scss";
import { Providers } from "./providers";
const volkhov = Volkhov({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-volkhov",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${volkhov.variable}`}>
        <Providers>
          {/* <Navbar/> */}
          {children}
        </Providers>
        {/* wrapping the app with SessionProvider, so that i can access the logged-in session anywheres */}
      </body>
    </html>
  );
}
