export const trips = [
  {
    title: "Santorini Summer Vacation",
    destination: "Santorini, Greece",
    startDate: "2025-07-10",
    endDate: "2025-07-17",
    budget: 1500,
    type: "VACATION",
    description: "",
  },
  {
    title: "Paris City Tour",
    destination: "Paris, France",
    startDate: "2025-09-05",
    endDate: "2025-09-10",
    budget: 1200,
    type: "VACATION",
    description: "",
  },
  {
    title: "Rome Adventure",
    startDate: "2025-10-12",
    endDate: "2025-10-15",
    destination: "Rome, Italy",
    budget: 800,
    type: "VACATION",
    description: "",
  },
  {
    title: "Barcelona Short Trip",
    startDate: "2025-06-20",
    endDate: "2025-06-23",
    destination: "Barcelona, Spain",
    budget: 950,
    type: "VACATION",
    description: "",
  },
  {
    title: "Athens City Weekend",
    startDate: "2025-06-05",
    endDate: "2025-06-07",
    destination: "Athens, Greece",
    budget: 400,
    type: "FAMILY",
    description: "",
  },
];
